#!/bin/bash

. /etc/default/pbs_licenses

if ! expr "$1" : '[A-Za-z0-9_][A-Za-z0-9_]*$' >/dev/null 2>&1 ;then
	echo 0
	exit
fi

if [ -x $ROOT/"$1"lic ];then
	exec $ROOT/"$1"lic
fi

#declare -a Vendor
#declare -a Feature
#declare -a Reserved
#declare -a LiceseFile

#
# Initialize arrays: Vendor daemon,
#                    Feature,
#                    licence k odecteni,
#                    licencni soubor,
#                    pozice pro nasobne licence (ve vypisu)
#
#Vendor=(ansyslmd FluentLm MSC MSC maplelmg maplelmg)
#Feature=(aa_t_a fluentall MARC MARC_Parallel Maple10 Maple11)
Vendor=(ansyslmd ansyslmd MSC MSC maplelmg maplelmg)
Feature=(aa_t_a aa_r MARC MARC_Parallel Maple10 Maple11)
Reserved=(10 6 3 0 0 0)
LicenseFile=(ansys.lic fluent.lic msc.lic msc.lic maple.lic maple.lic)
MultiLicPos=(11 11 11 11 11 11)

#
# Help
#
Usage ()
{
	echo "Usage:"
        echo "$0 FEATURE "
        echo "   (available features: ${Feature[*]})"
        exit 1

}

if [ $# -lt 1 ]
then
	Usage
fi

#
# Initialize variables
#
FEATURE=$1
VENDOR=""
RESERVED=""
LICENSEFILE=""
#LICDIR=/afs/zcu.cz/software/flexlm/licenses
LICDIR=$ROOT
#LMUTIL=/usr/local/bin/lmutil
LMUTIL=${LICDIR}/lmutil.timed
INDEX=0

#
# Search for feature
#
for str in ${Feature[*]} 
do
	if [ $FEATURE == $str ] 
	then 
		VENDOR=${Vendor[$INDEX]}
		RESERVED=${Reserved[$INDEX]}
		LICENSEFILE=${LicenseFile[$INDEX]}
		MULTILIC=${MultiLicPos[$INDEX]}
		break
	fi
	INDEX=$INDEX+1

done

if [ -z "$VENDOR" ]
then
	echo Feature \"$FEATURE\" not found.
	Usage
fi

if [ $FEATURE == MARC_Parallel ]
then
	RESULT=`$0 MARC`
	if [ $RESULT -lt 1 ]
	then
		echo 0
		exit  
	fi
fi

#
#
$LMUTIL lmstat -c $LICDIR/$LICENSEFILE -S $VENDOR | \
awk -v FTR=$FEATURE -v NUM=$RESERVED -v MLICF=$MULTILIC '
	BEGIN {FOUND_FEATURE = 0; TOTAL_LIC = 0; USED_LIC = 0}
	/^Users/ {if ( $3 == FTR":" ) {TOTAL_LIC = $6; FOUND_FEATURE = 1}
	           else {FOUND_FEATURE = 0}}
        /start/ {if ( FOUND_FEATURE == 1 ) {if ( NF == 11 ) {MLIC=MLICF-1} else {MLIC=MLICF} ;
					    {if ($MLIC == "") {CNTR_TMP = 1} else {CNTR_TMP = $MLIC}};
					    USED_LIC=USED_LIC+CNTR_TMP}}
	END {a=TOTAL_LIC - USED_LIC - NUM; if (a >0) {print a} else { print 0};}'

#END {printf("Total %d, Used %d, Reserved %d, Available %d\n", TOTAL_LIC,USED_LIC, NUM, TOTAL_LIC - USED_LIC - NUM)}'
#END {print TOTAL_LIC - USED_LIC - NUM}'
